# Generated by Django 6.1 on 2026-08-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codebase", "0003_codechunk"),
    ]

    operations = [
        migrations.AddField(
            model_name="codechunk",
            name="end_line",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="codechunk",
            name="start_line",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="codechunk",
            name="symbol_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="codechunk",
            name="symbol_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
